import styles from "@/styles/Home.module.css";
import TextField from "@mui/material/TextField";
import { ChangeEvent, useState } from "react";
import Button from "@mui/material/Button";
import Box from "@mui/material/Box";
import calculateIncomeTax from "./api/tax_calculator";
import Typography from "@mui/material/Typography";
import Stack from "@mui/material/Stack";

export default function Home() {
  const [income, setIncome] = useState(0);
  const [incomeError, setIncomeError] = useState(false);

  const [relief, setRelief] = useState(0);
  const [reliefError, setReliefError] = useState(false);

  const [originalTaxPayable, setOriginalTaxPayable] = useState(0);
  const [reducedTaxPayable, setReducedTaxPayable] = useState(0);

  return (
    <Stack spacing={2}>
      <Typography variant="h4">Tax Savings Viewer</Typography>
      <Stack spacing={2} className={styles.form}>
        <TextField
          label="Chargeable Income"
          value={income}
          onChange={handleIncomeChange}
          error={incomeError}
          helperText={
            incomeError ? "Chargeable income must be a positive integer" : ""
          }
          required
        />
        <TextField
          label="Tax Relief"
          value={relief}
          onChange={handleReliefChange}
          error={reliefError}
          helperText={
            reliefError
              ? "Tax relief must be a positive integer or empty"
              : "Leave empty if you have no tax relief"
          }
        />
        <Button variant="contained" color="primary" onClick={handleSubmit}>
          Compute Tax Payable
        </Button>
      </Stack>

      {originalTaxPayable !== 0 && (
        <Box>
          <Typography>
            Your Original Tax Payable is {originalTaxPayable}
          </Typography>
          <Typography>
            Your Reduced Tax Payable is {reducedTaxPayable}
          </Typography>
          <Typography>
            Savings: {originalTaxPayable - reducedTaxPayable}
          </Typography>
          <Typography>
            Savings in %:{" "}
            {((originalTaxPayable - reducedTaxPayable) / originalTaxPayable) *
              100}
            %
          </Typography>
        </Box>
      )}
    </Stack>
  );

  function handleIncomeChange(
    event: ChangeEvent<HTMLTextAreaElement | HTMLInputElement>
  ) {
    const value = event.target.value;
    setIncome(parseInt(value));
    setIncomeError(!/^\d+$/.test(value));
  }

  function handleReliefChange(
    event: ChangeEvent<HTMLTextAreaElement | HTMLInputElement>
  ) {
    const value = event.target.value;
    setRelief(parseInt(value));
    setReliefError(value !== "" && !/^\d+$/.test(value));
  }

  function handleSubmit() {
    const originalTaxPayable = calculateIncomeTax(income);
    const taxPayableAfterRelief = calculateIncomeTax(income, relief);

    setOriginalTaxPayable(originalTaxPayable);
    setReducedTaxPayable(taxPayableAfterRelief);
  }
  // return (
  //   <>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <meta name="viewport" content="width=device-width, initial-scale=1" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <main className={styles.main}>
  //       <div className={styles.description}>
  //         <p>
  //           Get started by editing&nbsp;
  //           <code className={styles.code}>src/pages/index.tsx</code>
  //         </p>
  //         <div>
  //           <a
  //             href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //             target="_blank"
  //             rel="noopener noreferrer"
  //           >
  //             By{' '}
  //             <Image
  //               src="/vercel.svg"
  //               alt="Vercel Logo"
  //               className={styles.vercelLogo}
  //               width={100}
  //               height={24}
  //               priority
  //             />
  //           </a>
  //         </div>
  //       </div>

  //       <div className={styles.center}>
  //         <Image
  //           className={styles.logo}
  //           src="/next.svg"
  //           alt="Next.js Logo"
  //           width={180}
  //           height={37}
  //           priority
  //         />
  //         <div className={styles.thirteen}>
  //           <Image
  //             src="/thirteen.svg"
  //             alt="13"
  //             width={40}
  //             height={31}
  //             priority
  //           />
  //         </div>
  //       </div>

  //       <div className={styles.grid}>
  //         <a
  //           href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //           target="_blank"
  //           rel="noopener noreferrer"
  //         >
  //           <h2 className={inter.className}>
  //             Docs <span>-&gt;</span>
  //           </h2>
  //           <p className={inter.className}>
  //             Find in-depth information about Next.js features and&nbsp;API.
  //           </p>
  //         </a>

  //         <a
  //           href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //           target="_blank"
  //           rel="noopener noreferrer"
  //         >
  //           <h2 className={inter.className}>
  //             Learn <span>-&gt;</span>
  //           </h2>
  //           <p className={inter.className}>
  //             Learn about Next.js in an interactive course with&nbsp;quizzes!
  //           </p>
  //         </a>

  //         <a
  //           href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //           target="_blank"
  //           rel="noopener noreferrer"
  //         >
  //           <h2 className={inter.className}>
  //             Templates <span>-&gt;</span>
  //           </h2>
  //           <p className={inter.className}>
  //             Discover and deploy boilerplate example Next.js&nbsp;projects.
  //           </p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //           target="_blank"
  //           rel="noopener noreferrer"
  //         >
  //           <h2 className={inter.className}>
  //             Deploy <span>-&gt;</span>
  //           </h2>
  //           <p className={inter.className}>
  //             Instantly deploy your Next.js site to a shareable URL
  //             with&nbsp;Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>
  //   </>
  // )
}
